### ISSUE TITLE
 No se levanta el container filebot-rpi

### ISSUE THREAD

**Issue by luislard** [pablokbs/plex-rpi#1]
Como el comando **/config/filebot-copy** está siendo ejecutado por el usuario abc en el contenedor de rtorrent (asi viene de la imagen :p), ese usuario no tiene privilegios para correr comandos de docker.  
**Solución**: en mi caso tuve que agregar el usuario **abc** al grupo de **docker** dentro del contenedor, luego en la _pi_ tuve que crear el usuario **abc** con el **id 911** que es como esta en el contenedor, también tuve que cambiar el **gid** del docker en el container para que igualara el **gid** del docker de la pi. Finalmente arreglado el conflicto de usuarios se levantó el container de **filebot-rpi**

**Comment by pablokbs** [comment]
Buenisimo, gracias por la explicación, me anoto para agregar esto al README.

**Comment by bibaldo** [comment]
@luislard podrias compartir los pasos y comandos?
