### ISSUE TITLE
Problema Flexget

### ISSUE THREAD

**Issue by ConradoChiesa** [pablokbs/plex-rpi#15]
hola, me saben decir porque se da este error y alguna solución?

standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Service 'flexget' failed to build: The command '/bin/sh -c apk add --update   tzdata   python   py-pip   ca-certificates   && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.0 transmissionrpc==0.11   && rm -rf /var/cache/apk/*' returned a non-zero code: 1

Gracias y saludos.
Conrado.

**Comment by ConradoChiesa** [comment]
Perdón no vi que habían preguntado lo mismo abajo lo cierro.

**Comment by pablokbs** [comment]
https://github.com/pablokbs/plex-rpi/issues/14
