### ISSUE TITLE
El container que se levanta de filebot-rpi se crea siempre y no se destruye

### ISSUE THREAD

**Issue by luislard** [pablokbs/plex-rpi#2]
Cuando se ejecuta el comando filebot-copy en la linea 
`FILEBOT="docker run -v /home/pi/plex-rpi/torrents-config/scripts:/scripts -v $MEDIA:$MEDIA -v /mnt/volume/some-path/downloads/incoming:/downloads/incoming pablokbs/filebot-rpi"`

Sería mejor colocar el flag **--rm** para que se cree y se auto destruya el container.

Quedaría 
`FILEBOT="docker run -v /home/pi/plex-rpi/torrents-config/scripts:/scripts -v $MEDIA:$MEDIA -v /mnt/volume/some-path//downloads/incoming:/downloads/incoming --rm pablokbs/filebot-rpi"`

**Comment by pablokbs** [comment]
Sip, esto deberia ser como vos decis, hacete un PR y lo mergeamos!
