### ISSUE TITLE
Consulta general

### ISSUE THREAD

**Issue by fabdelgado** [pablokbs/plex-rpi#22]
Como hacen para descargar en español directamente?, le ponen el nombre en español?

**Comment by pablokbs** [comment]
Tendrias que buscar un sitio con RSS que ponga series o peliculas en español (si es que querés descargarlo automaticamente con flexget) sino podes agregar los torrents "a mano" a transmission, eso hago yo con las peliculas. Y despues flexget los ordena y los mueve a dlrectorio de plex

**Comment by fabdelgado** [comment]
Genial muchas gracias

**Comment by bepece1** [comment]
> Tendrias que buscar un sitio con RSS que ponga series o peliculas en español (si es que querés descargarlo automaticamente con flexget) sino podes agregar los torrents "a mano" a transmission, eso hago yo con las peliculas. Y despues flexget los ordena y los mueve a dlrectorio de plex

Una pregunta, ¿es posible que flexget tenga la informacion en Español? Para que de esta forma pueda tener la sinopsis, el titulo, la portada, etc... en este idioma...
Actualmente uso sickchill, el cual se conecta al indexer "thetvdb" y te permite elegir el idioma.
Gracias por adelantado
