### ISSUE TITLE
Plex no reproduce los videos 

### ISSUE THREAD

**Issue by luislard** [pablokbs/plex-rpi#3]
Despues de haber configurado todo y teniendo los archivos en el directorio de media, plex los lee pero al tratar de reproducirlos recibo el siguiente error: 

**Este servidor no es lo suficientemente potente para convertir vídeo.**

Sólo pasa con algunos, por ej: los de Big Bang Theory del tutorial no los lee, pero uno de GOT si que lo lee.

Saludos

**Comment by pablokbs** [comment]
Hola! Perdón, recien veo esto (parece que no me llegan los mails de github) ahora me pongo a revisar tus issues y te respondo

**Comment by pablokbs** [comment]
Agregué esto al readme

**Comment by arpanet80** [comment]
Al terminar la instalación de los contenedores me salta el siguiente error:
`ERROR: unsatisfiable constraints:
  tinyxml2 (missing):
    required by: world[tinyxml2]

ERROR:` Service 'flexget' failed to build: The command '/bin/sh -c apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/main tinyxml2 &&     apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/community mediainfo &&     apk add --update ffmpeg &&     rm -rf /var/cache/apk/*' returned a non-zero code: 1`

Parece ser que se necesita tinyxml2, podrían darme una mano para instalarlo?

Gracias

**Comment by pablokbs** [comment]
Hola, estás usando [este Dockerfile](https://github.com/pablokbs/plex-rpi/blob/master/flexget-arm/Dockerfile)? es exactamente igual al que uso yo y me anduvo

**Comment by ddiaz2380** [comment]
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c apk add --update   tzdata   python   py-pip   ca-certificates   && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.0 transmissionrpc==0.11   && rm -rf /var/cache/apk/*' returned a non-zero code: 1

**Comment by landalv** [comment]
> standard_init_linux.go:211: exec user process caused "exec format error"
> The command '/bin/sh -c apk add --update   tzdata   python   py-pip   ca-certificates   && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.0 transmissionrpc==0.11   && rm -rf /var/cache/apk/*' returned a non-zero code: 1
> 
> 
> 

A mi me salta el mismo error, y tengo el Dockerfile q usas tu @pablokbs

**Comment by jaestsan** [comment]
Buenas, yo tengo varios problemas con transmission
1) modifico el fichero settings.json del directorio config y no coge los cambios, he parado el docker de transmission y nada
2) siempre me dice que el puerto 51413 esta closed en el UI de transmission pero lo tengo abierto en el router

Por si me podeis echar una mano

Gracias

**Comment by ddraco2001** [comment]
Hola  buen dia .. estoy intenando hacerlo funcionar en una RPI4 y un disco USB en formato NTFS.
Cuando levanta el plex da error..

Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --platformVersion arg Platform version string
  --vendor arg          Vendor string
  --device arg          Device string
  --model arg           Device model string
  --sentryUrl arg       Sentry URL to upload to
  --sentryKey arg       Sentry Key for the project
  --version arg         Version of the product
  --allowRetries arg    Whether we will allow retries
Critical: libusb_init failed
6 3000 /root/Library/Application Support
8192
Critical: libusb_init failed
 
Y todavia no encuentro al causa...
Saludos

**Comment by RobertTxapia** [comment]
Hola, cuando monte mi disco externo y voy a levantar el docker-compose me salta este error:

plex-rpi_plex_1 is up-to-date
plex-rpi_samba_1 is up-to-date
Starting plex-rpi_flexget_1 ...
Starting plex-rpi_flexget_1 ... error

ERROR: for plex-rpi_flexget_1  Cannot start service flexget: error while creating mount source path '/mnt/storage/media': mkdir /mnt/storage/media: read-only file system

ERROR: for flexget  Cannot start service flexget: error while creating mount source path '/mnt/storage/media': mkdir /mnt/storage/media: read-only file system
ERROR: Encountered errors while bringing up the project.

Un saludo.

**Comment by lcannobbio** [comment]
hola, tengo este gran error que me esta dando dolor de cabeza al correr el sort_movies

lcannobbio@debian:~/plex/plex-rpi$ sudo docker-compose exec flexget flexget execute --dump --tasks sort_movies

2024-01-31 23:49:34 VERBOSE  exec          sort_movies     Executing: if mediainfo "/downloads/complete/sunflower.mp4" | grep EAC3; then
   mkdir -p "/storage/pelis/Sunflower (2023)" && ffmpeg -hwaccel auto -y -i "/downloads/complete/sunflower.mp4" -map 0 -c:s copy -c:v copy -c:a ac3 -b:a 640k "/storage/pelis/Sunflower (2023)/Sunflower (2023).mp4"
else
  mkdir -p "Sunflower (2023)" && cp "/downloads/complete/sunflower.mp4" "Sunflower (2023)/Sunflower (2023).mp4"
fi
2024-01-31 23:49:35 INFO     exec          sort_movies     Stdout: mkdir: cannot create directory ‘Sunflower (2023)’: Permission denied

favor si me echan una mano lo agradecería muchísimo
