### ISSUE TITLE
filebot-rpi no se ejecuta

### ISSUE THREAD

**Issue by pablokbs** [pablokbs/plex-rpi#4]
Siguiendo este thread en youtube:

![image](https://user-images.githubusercontent.com/4028336/56317015-2c3d8880-6132-11e9-95cf-ec92cbfe79b3.png)

Será que esta relacionado con #1 ?

**Comment by nicomse** [comment]
soy yo con el que estabas hablando en youtube. Mis pasos para levantarlo fueron, hacer el clone desde el /home/pi. entre a la carpeta que se clono de este repo y levante docker. el servico de torrents y. samba y plex se levanta perfecto. Pero cuando bajo torrents no se me copian automaticamente a media con filebot copy como mostras en el video. Me fije en los logs y filebot copy no se ejecuta nunca segun los logs de docker. (espero que esta explicacion sirva para encontrar el problema)

**Comment by pablokbs** [comment]
@nicomse gracias por responder, podés probar meterte al contenedor de rtorrent y ejecutar el script a mano?:

```
$ docker-compose exec rtorrent bash
root@8772e77e7d65:/$ /config/filebot-copy ruta-a-tu-serie.mp4 series
```

Y pegate la salida en aca

**Comment by nicomse** [comment]
root@85bc4cad9955:/$ /config/filebot-copy downloads/incoming/Riverdale.US.S03E18.720p.HDTV.x264-LucidTV\[eztv\].mkv series
bash: /config/filebot-copy: Is a directory

me tiro esto como si fuera un directorio y no encontrara el script

**Comment by pablokbs** [comment]
Ese es el problema. Hiciste algún cambio en el docker-compose? Me
mostrarias tu archivo?

**Comment by nicomse** [comment]
nop, ningun cambio le hice, creo que el unico que le hice fue probar para cambiar los permisos de samba para poder draggear archivos desde la mac pero eso no creo que afecte. igual te lo paso aver que opinas 
https://pastebin.com/v70r65GN
tengo el docker-compose.yml en la carpeta plex-rpi (que es la que me crea el repo cuando lo clono). estoy atento a tus comentarios

**Comment by pablokbs** [comment]
Veo que en el docker-compose tenes esta ruta:

```
    volumes:
      - /home/pi/torrents-config:/config
```

Tu directorio  `torrents-config` está en `/home/pi`?

**Comment by nicomse** [comment]
el torrents-config esta en /home/pi/plex-rpi (no modifique nigun directorio del docker compose del repo como tecomentaba antes )pero cuando hago docker-compose up -d se me genera una carpeta en el home directory. Te adjunto una imagen de muestra. 
https://pasteboard.co/IaSu9vO.png
https://pasteboard.co/IaSuhxP.png

**Comment by pablokbs** [comment]
Claro, ese es el problema, tenes que modificar el docker-compose para que apunte al directorio donde vos tenes tus archivos, o mover todo a donde docker-compose los va a buscar

**Comment by nicomse** [comment]
cambie en el docker compose a la carpeta del repo pero me sigue sin funcionar el filebot copy

**Comment by nicomse** [comment]
en los logs no veo ninguna actividad cuando bajo un torrent

**Comment by pablokbs** [comment]
Tenes que hacer un `docker-compose down` y `docker-compose rm -f -v` ... después hacé un `docker-compose up -d`

**Comment by nicomse** [comment]
estoy en eso aver que onda, te hago un update del status aver en que resulto

**Comment by nicomse** [comment]
https://pasteboard.co/IaTOdXV.png
https://pastebin.com/kkmBfkhg
Este es mi output de la consola y este es mi docker compose, nose que esta mal la verdad jaja
en el log en ningun momento se ejecuta el filebot copy

**Comment by pablokbs** [comment]
Probá nuevamente si el archivo es un archivo o directorio dentro del contenedor, y probá corriendolo a mano

**Comment by nicomse** [comment]
ahi lo corri manualmente y me funciono!, como hago para que me corra automaticamente cada vez que se baja un torrent?

**Comment by pablokbs** [comment]
Bien, eso ya está onfigurado en el `.rtorrent.rc`

**Comment by pablokbs** [comment]
Ahi arreglé el readme para que sea mas claro y esto no le pase a otra persona, volvelo a abrir si tenes otro problema. Saludos

**Comment by bibaldo** [comment]
@nicomse se te soluciono el problema de que no corre automaticamente? y si pudiste, como lo hiciste?

**Comment by nicomse** [comment]
@bibaldo la ultima vez que lo corri (hace relativamente bastante) no pude, hace poco compre una micro sd mas rapida para descartar cualquier cosa.

**Comment by bibaldo** [comment]
@nicomse nono, tiene que ver con esto https://github.com/pablokbs/plex-rpi/issues/1

**Comment by bibaldo** [comment]
@nicomse logre hacerlo funcionar
