### ISSUE TITLE
Me aparece plex web no plex server

### ISSUE THREAD

**Issue by Hser2bio** [pablokbs/plex-rpi#40]
Hola

cuando acceso a la dirección del servidor: XXX.XXX.XXX:32400/web me aparece esto en vez de lo que le aparece el

![image](https://github.com/pablokbs/plex-rpi/assets/38903436/0709191a-1eac-4098-aa75-b0e3ece0380b)

alguna idea?

**Comment by gumonet** [comment]
Si estas accediendo desde un equipo diferente a donde tienes instalado el plex creo que por seguridad inicialmente tiene bloqueadas las conexiones remotas, en lo personal lo solucioné creando un tunnel ssh
`ssh -L 32400:localhost:32400 user@<PLEX_SERVER_IP>`

Posteriormente accede a localhost:32400/web y debería andar bien

**Comment by Hser2bio** [comment]
Solucionado @gumonet  thanks
